import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 140
dimensions.lines = 60


padding.x = 10
padding.y = 10

title = "thefordz"
decorations = "Buttonless"

opacity = 0.2
blur = true


option_as_alt = "Both"

[font]

normal.family = "JetBrainsMonoNL Nerd Font"
#
# normal.family = "HackGen Console NF"
#
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "RobotoMono Nerd Font"
# normal.family = "CaskaydiaCove Nerd Font"


size = 20

